version: "3"
services:
  nano35-instance-api:
    image: bushemi2021/nano35.instance.api:latest
    ports:
      - "8000:80"
    networks:
      - nano35-network

  nano35-instance-processor:
    image: bushemi2021/nano35.instance.processor:latest
    networks:
      - nano35-network

networks:
  nano35-network:
    driver: bridge