apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano35-instance-processor
  namespace: nano35
spec:
  replicas: 1
  selector:
    matchLabels:
      type: nano35-processor
      app: nano35-instance-processor
  template:
    metadata:
      labels:
        app: nano35-instance-processor
    spec:
      containers:
      - image: bushemi2021/nano35.instance.processor:latest
        name: nano35-instance-processor
        ports:
        - containerPort: 80
      restartPolicy: Always